devtools::install_version('shiny', version = '1.5.0', repos = 'http://cran.us.r-project.org')
devtools::install_version('shinyBS', version = '0.61', repos = 'http://cran.us.r-project.org')
devtools::install_version('shinyjs', version = '2.0.0', repos = 'http://cran.us.r-project.org')
devtools::install_version('shinyalert', version = '2.0.0', repos = 'http://cran.us.r-project.org')
devtools::install_version('shinydashboard', version = '0.7.1', repos = 'http://cran.us.r-project.org')
devtools::install_version('shinycssloaders', version = '1.0.0', repos = 'http://cran.us.r-project.org')
devtools::install_version('DT', version = '0.15', repos = 'http://cran.us.r-project.org')
devtools::install_version('data.table', version = '1.13.0')
devtools::install_version('DSI', version = '1.1.0', repos = 'http://cran.us.r-project.org')
devtools::install_version('DSOpal', version = '1.1.0', repos = 'http://cran.us.r-project.org')
devtools::install_version('stringr', version = '1.4.0', repos = 'http://cran.us.r-project.org')
install.packages('dsBaseClient', repos = c(getOption('repos'), 'http://cran.obiba.org'), dependencies = TRUE)
devtools::install_version('ggrepel', version = '0.8.2', repos = 'http://cran.us.r-project.org')
devtools::install_github('isglobal-brge/dsOmicsClient', force = TRUE)
devtools::install_version('shinyWidgets', version = '0.5.4', repos = 'http://cran.us.r-project.org')